# Feature engineering

This notebook focuses on developing features for the model of predicting the sales potential of new locations.

 Planned features:

Competition:
- competitor_count_1500m — number of competitor locations in the 1500-meter radius
- nearest_competitor_m — distance to the nearest competitor

POI:
- poi_count_1500m — total number of POIs
- poi_[category]_count_1500m — total number of POIs per category
- nearest_poi_m - distance to the nearest POI
- nearest_poi_[category]_m - distance to the nearest category of POI

Buildings:
- building_count_1500m — number of buildings
- residential_ratio_1500m — ratio of residential buildings

Population:
- population_1500m — total number of residents

Footfall:
- signals_1500m — number of signals
- unique_users_1500m — unique users

The radius of 1500 meters was chosen empirically and can be changed by modifying the `RADIUS` variable below and rerunning the notebook.

In [1]:
import geopandas as gpd
from pathlib import Path

PROCESSED_PATH = Path("../data/processed")

gdf_locations    = gpd.read_parquet(PROCESSED_PATH / "gdf_locations.parquet")
gdf_competitors  = gpd.read_parquet(PROCESSED_PATH / "gdf_competitors.parquet")
gdf_poi          = gpd.read_parquet(PROCESSED_PATH / "gdf_poi.parquet")
gdf_area         = gpd.read_parquet(PROCESSED_PATH / "gdf_area.parquet")
gdf_districts    = gpd.read_parquet(PROCESSED_PATH / "gdf_districts.parquet")
gdf_buildings    = gpd.read_parquet(PROCESSED_PATH / "gdf_buildings.parquet")
gdf_population   = gpd.read_parquet(PROCESSED_PATH / "gdf_population.parquet")

In [2]:
RADIUS = 1500

Specific methods of computing each group of features is present in `src/features.py`. The exact process of computing each feature is described in the comments for each method.

In [3]:
from src.features import compute_competitor_features, compute_poi_features, compute_buildings_features, compute_population_features, compute_footfall_features

#### Competitors

In [4]:
competitor_features = compute_competitor_features(gdf_locations, gdf_competitors, RADIUS)

In [5]:
competitor_features

   location_id  competitor_count_1500m  nearest_competitor_m
0      LOC_001                       1            262.795371
1      LOC_002                       0           2567.458932
2      LOC_003                       2            619.198805
3      LOC_004                       0           9153.895298
4      LOC_005                       1           1211.453292
5      LOC_006                       0           2383.421789
6      LOC_007                       0           2389.236196
7      LOC_008                       0           3604.922988
8      LOC_009                       0           2946.215401
9      LOC_010                       0           1854.202830
10     LOC_011                       0           3391.347307
11     LOC_012                       0           5548.279960
12     LOC_013                       1             67.408448
13     LOC_014                       1           1012.438181
14     LOC_015                       1           1200.251735
15     LOC_016                       1           1419.992446
16     LOC_017                       1            505.994634
17     LOC_018                       1           1469.834405
18     LOC_019                       2           1153.726557
19     LOC_020                       1            526.079237
20     LOC_021                       0           1730.796102
21     LOC_022                       1           1181.803056
22     LOC_023                       0           3070.713800
23     LOC_024                       0          12846.160188
24     LOC_025                       0           3661.191951
25     LOC_026                       0           5132.222015
26     LOC_027                       0           2071.145796
27     LOC_028                       0           2901.523481
28     LOC_029                       0           2581.493426
29     LOC_030                       0           1640.658150
30     LOC_031                       0           2308.646379
31     LOC_032                       0           2864.242280
32     LOC_033                       1           1278.928903
33     LOC_034                       0           2411.443257
34     LOC_035                       3            600.896245
35     LOC_036                       1             42.173981
36     LOC_037                       0           7830.150175
37     LOC_038                       1            204.584092
38     LOC_039                       4            752.347560
39     LOC_040                       1           1209.419806
40     LOC_041                       0          13842.306595
41     LOC_042                       0           1691.516083
42     LOC_043                       1           1398.407195
43     LOC_044                       0           2204.183344
44     LOC_045                       1           1316.696074
45     LOC_046                       1            267.192979
46     LOC_047                       0           3718.122394
47     LOC_048                       1            703.032763
48     LOC_049                       1            552.719802
49     LOC_050                       0           1769.024246

In [6]:
print(competitor_features[f'competitor_count_{RADIUS}m'].value_counts())
competitor_features.info()
competitor_features.describe()

competitor_count_1500m
0    27
1    19
2     2
3     1
4     1
Name: count, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   location_id             50 non-null     object
 1   competitor_count_1500m  50 non-null     int64
 2   nearest_competitor_m    50 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.3+ KB

       competitor_count_1500m  nearest_competitor_m
count               50.000000             50.000000
mean                 0.600000           2541.437919
std                  0.832993           2867.428153
min                  0.000000             42.173981
25%                  0.000000           1047.760275
50%                  0.000000           1711.156093
75%                  1.000000           2892.203181
max                  4.000000          13842.306595

#### POIs

In [7]:
poi_features = compute_poi_features(gdf_locations, gdf_poi, RADIUS)
poi_features

,location_id,poi_count_1500m,nearest_poi_m,poi_restaurant_count_1500m,nearest_poi_restaurant_m,poi_bank_count_1500m,nearest_poi_bank_m,poi_school_count_1500m,nearest_poi_school_m,poi_bus_stop_count_1500m,nearest_poi_bus_stop_m,poi_park_count_1500m,nearest_poi_park_m,poi_pharmacy_count_1500m,nearest_poi_pharmacy_m,poi_hospital_count_1500m,nearest_poi_hospital_m,poi_mall_count_1500m,nearest_poi_mall_m
0,LOC_001,0,1644.258581,0,3508.276856,0,4935.923724,0,5093.826731,0,1644.258581,0,2085.040228,0,5116.461759,0,6887.945370,0,10483.383593
1,LOC_002,11,442.687835,4,834.054653,0,7855.760495,3,442.687835,0,2139.914263,1,1264.122489,2,679.653896,1,1469.660936,0,7860.430423
2,LOC_003,2,176.808447,0,1924.769849,0,1564.633471,0,2262.431183,1,524.253413,0,2063.400799,0,2330.359427,0,2622.969514,1,176.808447
3,LOC_004,0,2041.842112,0,11708.981182,0,14548.715383,0,8757.348413,0,6385.916456,0,2041.842112,0,11188.412501,0,12702.138624,0,13938.294690
4,LOC_005,1,1081.644470,0,5302.691028,0,2048.529943,0,1955.442974,0,1586.395355,0,2026.654262,0,3828.897338,1,1081.644470,0,6566.012106
5,LOC_006,5,457.328429,1,1066.233527,0,5718.489810,1,457.328429,1,594.385991,0,3299.390423,0,6434.450495,2,856.805877,0,4091.387108
6,LOC_007,1,794.507330,0,1747.796648,0,2557.193166,0,1782.480673,0,3740.160704,0,4480.726139,0,2504.708304,1,794.507330,0,8035.228268
7,LOC_008,1,85.340871,0,3378.313139,1,85.340871,0,11357.258138,0,6772.501741,0,5000.899037,0,11866.487002,0,11582.301804,0,4696.770810
8,LOC_009,8,220.296106,2,1283.429958,0,7598.074758,4,558.759084,0,2337.700533,1,955.976278,1,220.296106,0,1926.974884,0,8238.469173
9,LOC_010,6,76.985326,0,3590.490489,1,110.580686,1,132.079638,2,721.354432,1,76.985326,0,2091.077229,1,922.700778,0,6850.431334
10,LOC_011,1,1242.560966,0,20671.873089,0,14607.955095,0,3727.598038,0,3228.687566,1,1242.560966,0,5708.796017,0,20515.138507,0,13680.132198
11,LOC_012,0,2924.723472,0,5387.059588,0,9064.415708,0,4546.587072,0,2924.723472,0,9102.013143,0,4536.179588,0,3957.872170,0,6979.298982
12,LOC_013,1,1444.252409,0,5791.439169,0,2973.845868,1,1444.252409,0,2386.363622,0,2590.129455,0,8123.293824,0,4694.039379,0,3430.888944
13,LOC_014,4,1137.727313,1,1280.148184,0,1857.943676,0,1569.965904,0,3353.319637,0,3774.744444,1,1248.500993,2,1137.727313,0,4050.548455
14,LOC_015,6,68.978531,2,1284.763181,0,9082.846532,1,897.540660,0,1999.002673,0,3047.901724,1,860.261902,1,881.607403,1,68.978531
15,LOC_016,2,1095.553946,1,1095.553946,0,3850.930563,0,2640.715931,0,3308.594105,0,1750.728706,0,3193.699584,0,4668.348947,1,1460.026544
16,LOC_017,8,371.448533,4,1320.568704,0,5764.611140,2,371.448533,0,3317.892316,0,3353.383608,1,1434.768903,1,1386.595943,0,5769.187875
17,LOC_018,0,1577.953516,0,2876.298127,0,9580.212125,0,5009.169651,0,4721.195564,0,1910.330170,0,12125.749865,0,1577.953516,0,9787.736238
18,LOC_019,7,228.779964,1,228.779964,3,262.195557,1,899.663889,0,1961.383640,0,4380.885841,2,468.367144,0,2233.313529,0,8898.473262
19,LOC_020,4,690.541767,0,1534.418841,1,1393.508749,1,1108.444610,0,2103.941078,0,3414.378062,2,690.541767,0,1702.768607,0,1801.688387
20,LOC_021,1,1303.463132,0,1915.922219,0,4336.821244,0,1988.669866,0,3456.798777,1,1303.463132,0,3873.149672,0,5282.030834,0,1782.437480
21,LOC_022,2,1218.138532,1,1302.236785,0,2113.341258,0,2480.988922,0,2642.873511,0,3319.847072,1,1218.138532,0,1777.614637,0,5036.422024
22,LOC_023,4,594.346163,1,594.346163,1,1244.719613,0,4947.034345,0,3451.823875,1,873.678221,0,1675.121119,1,1094.121088,0,8271.983517
23,LOC_024,1,128.926819,0,2821.307589,1,128.926819,0,2516.758455,0,12713.799657,0,20524.838522,0,13094.836681,0,19679.770591,0,18864.533654
24,LOC_025,1,1438.141983,0,3309.574870,0,8558.242846,0,4220.038700,1,1438.141983,0,1532.363010,0,10003.541315,0,4169.422944,0,7711.271654
25,LOC_026,0,1661.786057,0,6803.892435,0,7634.938498,0,2917.348129,0,1661.786057,0,7675.965534,0,3427.791723,0,4253.143301,0,8493.079724
26,LOC_027,0,1498.829585,0,3672.031493,0,8836.685258,0,1498.829585,0,1913.943200,0,3827.079054,0,1605.481918,0,3170.845806,0,4628.520387
27,LOC_028,0,4023.653180,0,4220.043817,0,5268.112262,0,7330.973614,0,4656.096060,0,4023.653180,0,4791.340757,0,6071.446824,0,10955.128873
28,LOC_029,6,203.850066,2,203.850066,0,10336.284117,1,664.038826,0,1548.254807,0,3464.179814,1,1053.583118,1,1052.377683,1,1317.365704
29,LOC_030,0,1895.686735,0,3377.424118,0,1895.686735,0,2039.682663,0,4364.489861,0,2825.206177,0,3553.087017,0,4809.611999,0,3340.170920
30,LOC_031,0,1616.502301,0,1616.502301,0,3625.721950,0,4117.250805,0,3458.983270,0,4312.835848,0,2802.991556,0,3398.915391,0,6673.636374
31,LOC_032,1,674.679067,0,6967.890804,1,674.679067,0,10423.829672,0,5876.519533,0,10180.303908,0,10611.704184,0,8712.964856,0,11685.006472
32,LOC_033,1,459.207329,0,7081.619162,0,6835.388095,1,459.207329,0,1636.075141,0,15307.656157,0,12333.091693,0,18619.663319,0,18832.701694
33,LOC_034,9,499.623243,4,523.439033,0,7465.078591,2,857.773166,1,1413.098147,0,2026.616136,1,499.623243,1,589.106570,0,7468.889697
34,LOC_035,2,1216.028008,0,1618.851041,1,1216.028008,0,1919.250325,1,1437.259511,0,2291.238896,0,1557.175837,0,2508.663712,0,2685.053626
35,LOC_036,2,409.082289,0,1904.364722,0,4248.079301,1,409.082289,0,2797.456065,1,966.492543,0,4217.931357,0,3531.935578,0,2469.607714
36,LOC_037,0,3781.631060,0,8324.822065,0,4995.906049,0,3781.631060,0,5580.653894,0,10483.349072,0,6974.283500,0,8347.620496,0,8501.454620
37,LOC_038,0,1936.586659,0,11784.602031,0,5360.623940,0,4805.482412,0,1936.586659,0,5891.471494,0,4927.488002,0,11647.230883,0,5354.021670
38,LOC_039,11,758.836767,6,824.071179,1,758.836767,2,1380.714601,0,2043.568261,1,847.772152,0,1752.349393,1,1051.706895,0,1693.477923
39,LOC_040,0,1566.951256,0,17948.513621,0,1566.951256,0,20276.500680,0,3748.501677,0,12894.628881,0,6872.280066,0,16846.514949,0,2624.954416
40,LOC_041,2,719.436460,0,20968.450341,1,975.175971,1,719.436460,0,9448.901048,0,7278.067143,0,8789.365085,0,15514.845702,0,15750.176520
41,LOC_042,1,1109.241420,0,3810.667056,0,2187.914663,0,1967.905951,1,1109.241420,0,3383.899523,0,1535.908629,0,4341.606978,0,1709.353238
42,LOC_043,4,826.073550,2,826.073550,2,1468.940496,0,1933.870397,0,2545.202490,0,3272.333831,0,1618.974867,0,3563.464247,0,8900.022365
43,LOC_044,0,2783.305526,0,4178.423254,0,4603.463166,0,2783.305526,0,3307.413660,0,4546.229765,0,2859.150318,0,5022.601537,0,7845.796740
44,LOC_045,9,551.714608,4,583.858953,0,6407.958755,3,848.150175,0,2490.740140,0,2807.067859,1,669.307398,1,551.714608,0,6412.042978
45,LOC_046,1,1498.071675,0,4130.215413,1,1498.071675,0,1901.162412,0,4077.478827,0,1752.450433,0,5907.582094,0,4000.776483,0,5819.529036
46,LOC_047,1,1303.909411,0,4618.639072,0,3376.617441,1,1303.909411,0,3245.970346,0,8835.199022,0,3871.003151,0,2489.063414,0,5924.393308
47,LOC_048,5,281.150277,1,281.150277,1,503.176548,1,1159.501570,0,8841.432339,0,5678.481382,0,1837.248478,2,361.858858,0,5413.645499
48,LOC_049,6,200.096943,0,1596.531552,1,1166.754650,2,1090.097802,0,1977.213862,0,2655.251487,2,200.096943,0,1787.424353,1,1384.160631
49,LOC_050,0,3215.189555,0,3665.610009,0,10597.467382,0,7043.959824,0,3215.189555,0,4671.452597,0,6160.037178,0,6683.287528,0,6671.091983

In [8]:
for cat in gdf_poi['category'].unique():
    print(poi_features[f'poi_{cat}_count_{RADIUS}m'].value_counts())
poi_features.info()
poi_features.describe()

poi_restaurant_count_1500m
0    34
1     7
4     4
2     4
6     1
Name: count, dtype: int64
poi_bank_count_1500m
0    36
1    12
3     1
2     1
Name: count, dtype: int64
poi_school_count_1500m
0    31
1    12
2     4
3     2
4     1
Name: count, dtype: int64
poi_bus_stop_count_1500m
0    43
1     6
2     1
Name: count, dtype: int64
poi_park_count_1500m
0    42
1     8
Name: count, dtype: int64
poi_pharmacy_count_1500m
0    38
1     8
2     4
Name: count, dtype: int64
poi_hospital_count_1500m
0    36
1    11
2     3
Name: count, dtype: int64
poi_mall_count_1500m
0    45
1     5
Name: count, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   location_id                 50 non-null     object
 1   poi_count_1500m             50 non-null     int64
 2   nearest_poi_m               50 non-null     float64
 3   poi_restaurant_count_1500m  50 non-null     int64
 4   nearest_poi_restaurant_m    50 non-null     float64
 5   poi_bank_count_1500m        50 non-null     int64
 6   nearest_poi_bank_m          50 non-null     float64
 7   poi_school_count_1500m      50 non-null     int64
 8   nearest_poi_school_m        50 non-null     float64
 9   poi_bus_stop_count_1500m    50 non-null     int64
 10  nearest_poi_bus_stop_m      50 non-null     float64
 11  poi_park_count_1500m        50 non-null     int64
 12  nearest_poi_park_m          50 non-null     float64
 13  poi_pharmacy_count_1500m    50 non-null     int64
 14  nearest_poi_pharmacy_m      50 non-null     float64
 15  poi_hospital_count_1500m    50 non-null     int64
 16  nearest_poi_hospital_m      50 non-null     float64
 17  poi_mall_count_1500m        50 non-null     int64
 18  nearest_poi_mall_m          50 non-null     float64
dtypes: float64(9), int64(9), object(1)
memory usage: 7.5+ KB

,poi_count_1500m,nearest_poi_m,poi_restaurant_count_1500m,nearest_poi_restaurant_m,poi_bank_count_1500m,nearest_poi_bank_m,poi_school_count_1500m,nearest_poi_school_m,poi_bus_stop_count_1500m,nearest_poi_bus_stop_m,poi_park_count_1500m,nearest_poi_park_m,poi_pharmacy_count_1500m,nearest_poi_pharmacy_m,poi_hospital_count_1500m,nearest_poi_hospital_m,poi_mall_count_1500m,nearest_poi_mall_m
count,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.00000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,2.760000,1143.567192,0.740000,4145.817302,0.340000,4506.965995,0.600000,3096.028295,0.160000,3275.748776,0.160000,4346.303301,0.32000,4298.892569,0.340000,5090.687339,0.100000,6621.682116
std,3.178756,939.156015,1.396935,4821.563298,0.626295,3726.922711,0.947607,3563.147009,0.421852,2325.369397,0.370328,3952.582690,0.62073,3676.879775,0.592814,5337.100689,0.303046,4390.363725
min,0.000000,68.978531,0.000000,203.850066,0.000000,85.340871,0.000000,132.079638,0.000000,524.253413,0.000000,76.985326,0.00000,200.096943,0.000000,361.858858,0.000000,68.978531
25%,0.000000,446.347983,0.000000,1283.763264,0.000000,1476.223291,0.000000,947.272368,0.000000,1919.604065,0.000000,2026.625667,0.00000,1541.225431,0.000000,1407.362191,0.000000,3362.850426
50%,1.000000,1088.599208,0.000000,2848.802858,0.000000,3738.326257,0.000000,1944.656686,0.000000,2720.164788,0.000000,3309.618747,0.00000,3310.745654,0.000000,3465.425485,0.000000,6489.027542
75%,4.750000,1549.920838,1.000000,4518.990258,1.000000,7307.655967,1.000000,4033.345869,0.000000,3669.866345,0.000000,4640.146889,0.00000,6096.923407,1.000000,5874.092827,0.000000,8437.805672
max,11.000000,4023.653180,6.000000,20968.450341,3.000000,14607.955095,4.000000,20276.500680,2.000000,12713.799657,1.000000,20524.838522,2.00000,13094.836681,2.000000,20515.138507,1.000000,18864.533654

#### Buildings

In [9]:
buildings_features = compute_buildings_features(gdf_locations, gdf_buildings, RADIUS)

In [10]:
buildings_features

   location_id  building_count_1500m  residential_ratio_1500m
0      LOC_001                  1345                 0.591822
1      LOC_002                  4861                 0.565110
2      LOC_003                  2737                 0.471319
3      LOC_004                  1784                 0.613789
4      LOC_005                  2437                 0.499795
5      LOC_006                  2640                 0.628788
6      LOC_007                  2818                 0.521292
7      LOC_008                  1949                 0.632632
8      LOC_009                  4801                 0.605082
9      LOC_010                  4910                 0.558045
10     LOC_011                  1031                 0.520854
11     LOC_012                  2217                 0.534506
12     LOC_013                  2447                 0.597058
13     LOC_014                  3148                 0.703939
14     LOC_015                  3423                 0.562080
15     LOC_016                  3239                 0.655758
16     LOC_017                  3455                 0.577135
17     LOC_018                  2009                 0.622698
18     LOC_019                  5019                 0.504483
19     LOC_020                  2885                 0.618718
20     LOC_021                  3840                 0.683854
21     LOC_022                  3319                 0.736969
22     LOC_023                  4408                 0.623412
23     LOC_024                  2004                 0.660679
24     LOC_025                  3736                 0.736617
25     LOC_026                  1922                 0.520812
26     LOC_027                  2822                 0.587881
27     LOC_028                   770                 0.596104
28     LOC_029                  4740                 0.541983
29     LOC_030                  2590                 0.584170
30     LOC_031                  2801                 0.717244
31     LOC_032                  2639                 0.619553
32     LOC_033                  4035                 0.599009
33     LOC_034                  4874                 0.572425
34     LOC_035                  1713                 0.472855
35     LOC_036                  3230                 0.669040
36     LOC_037                  1272                 0.629717
37     LOC_038                   621                 0.294686
38     LOC_039                  3531                 0.504673
39     LOC_040                  1864                 0.575644
40     LOC_041                  1514                 0.581242
41     LOC_042                  1658                 0.628468
42     LOC_043                  2856                 0.441176
43     LOC_044                  2038                 0.586359
44     LOC_045                  5328                 0.616929
45     LOC_046                  1257                 0.583930
46     LOC_047                  1983                 0.633888
47     LOC_048                  5824                 0.507555
48     LOC_049                  3780                 0.662698
49     LOC_050                   945                 0.696296

In [11]:
buildings_features.info()
buildings_features.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   location_id              50 non-null     object
 1   building_count_1500m     50 non-null     int64
 2   residential_ratio_1500m  50 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.3+ KB

       building_count_1500m  residential_ratio_1500m
count             50.000000                50.000000
mean            2861.380000                 0.589015
std             1303.197307                 0.080394
min              621.000000                 0.294686
25%             1928.750000                 0.545999
50%             2769.000000                 0.593963
75%             3684.750000                 0.629485
max             5824.000000                 0.736969

#### Population

In [12]:
population_features = compute_population_features(gdf_locations, gdf_population, RADIUS)

In [13]:
population_features

   location_id  population_1500m
0      LOC_001             15892
1      LOC_002             37983
2      LOC_003             18939
3      LOC_004              3574
4      LOC_005             30322
5      LOC_006             37003
6      LOC_007             23388
7      LOC_008              8781
8      LOC_009             34019
9      LOC_010             42146
10     LOC_011              1968
11     LOC_012              5872
12     LOC_013             20426
13     LOC_014             20148
14     LOC_015             21662
15     LOC_016             32672
16     LOC_017             32592
17     LOC_018             35465
18     LOC_019             42643
19     LOC_020             36366
20     LOC_021             28810
21     LOC_022             27802
22     LOC_023             27195
23     LOC_024              4983
24     LOC_025             14994
25     LOC_026              4925
26     LOC_027             22010
27     LOC_028              4436
28     LOC_029             21783
29     LOC_030             34534
30     LOC_031              9856
31     LOC_032              5460
32     LOC_033             14127
33     LOC_034             34930
34     LOC_035             59635
35     LOC_036             44337
36     LOC_037              2092
37     LOC_038              4420
38     LOC_039             32852
39     LOC_040              8963
40     LOC_041              3194
41     LOC_042             54921
42     LOC_043             27958
43     LOC_044             16100
44     LOC_045             44178
45     LOC_046             13839
46     LOC_047              9531
47     LOC_048             17889
48     LOC_049             49721
49     LOC_050              2180

In [14]:
population_features.info()
population_features.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   location_id       50 non-null     object
 1   population_1500m  50 non-null     int64
dtypes: int64(1), object(1)
memory usage: 928.0+ bytes

       population_1500m
count         50.000000
mean       22990.320000
std        15308.202973
min         1968.000000
25%         9105.000000
50%        21722.500000
75%        34405.250000
max        59635.000000

#### Footfall

In [15]:
import json

with open('../data/processed/analysis_bbox.json') as f:
    ANALYSIS_BBOX = json.load(f)

In [16]:
BBOX_FILTER = f"""
    CAST(latitude AS FLOAT) BETWEEN {ANALYSIS_BBOX['lat_min']} AND {ANALYSIS_BBOX['lat_max']}
    AND CAST(longitude AS FLOAT) BETWEEN {ANALYSIS_BBOX['lng_min']} AND {ANALYSIS_BBOX['lng_max']}
"""

DATE_FILTER = """
    YEAR(TRY_TO_TIMESTAMP(occured_at)) = 2020
    AND MONTH(TRY_TO_TIMESTAMP(occured_at)) = 7
"""

BASE_FILTER = f"""
    {BBOX_FILTER} AND {DATE_FILTER}
"""

In [17]:
import pandas as pd

FOOTFALL_CACHE = Path('../data/processed/footfall_features.parquet')

if FOOTFALL_CACHE.exists():
    footfall_features = pd.read_parquet(FOOTFALL_CACHE)
    print("Loaded from cache")
else:
    footfall_features = compute_footfall_features(gdf_locations, BASE_FILTER, RADIUS)
    footfall_features.to_parquet(FOOTFALL_CACHE)
    print("Computed and cached")

Computed and cached

In [18]:
footfall_features

   location_id  signals_1500m  unique_users_1500m
0      LOC_019         225231                3349
1      LOC_037           2572                 163
2      LOC_045         203124                2059
3      LOC_014          48558                 934
4      LOC_033          47229                 996
5      LOC_020          84976                1433
6      LOC_013         116090                1057
7      LOC_040          55600                1010
8      LOC_002         224210                2366
9      LOC_025          50988                 972
10     LOC_003          59993                1401
11     LOC_006         104499                1331
12     LOC_038          15551                 236
13     LOC_039         132251                2224
14     LOC_004           4966                 159
15     LOC_010         214271                2298
16     LOC_021          73701                1432
17     LOC_046          49115                 778
18     LOC_041          21413                 528
19     LOC_026          10722                 236
20     LOC_027          72487                1259
21     LOC_031          40593                 967
22     LOC_016          84713                1352
23     LOC_018         146888                1790
24     LOC_043         132241                2512
25     LOC_024           8576                 332
26     LOC_008          23999                 377
27     LOC_005         141038                1587
28     LOC_032           9411                 358
29     LOC_036         165864                1817
30     LOC_017         160777                1549
31     LOC_023          93371                1410
32     LOC_022          95020                1445
33     LOC_035         161861                2133
34     LOC_029          68156                1143
35     LOC_028          13236                 176
36     LOC_044          59566                 780
37     LOC_012          12379                 282
38     LOC_009         177293                2180
39     LOC_001          45916                 689
40     LOC_042         148809                1646
41     LOC_015          94758                1428
42     LOC_034         194944                2176
43     LOC_007          87403                 973
44     LOC_049         144699                2056
45     LOC_047          30866                 431
46     LOC_030         116232                1398
47     LOC_048          65732                1190
48     LOC_050           3556                 365
49     LOC_011          10689                 366

In [19]:
footfall_features.info()
footfall_features.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   location_id         50 non-null     object
 1   signals_1500m       50 non-null     int64
 2   unique_users_1500m  50 non-null     int64
dtypes: int64(2), object(1)
memory usage: 1.3+ KB

       signals_1500m  unique_users_1500m
count      50.000000           50.000000
mean    87122.660000         1222.580000
std     65478.587593          745.034997
min      2572.000000          159.000000
25%     33297.750000          568.250000
50%     73094.000000         1224.500000
75%    138841.250000         1631.250000
max    225231.000000         3349.000000

In [20]:
features_df = (
    gdf_locations[['location_id', 'lat', 'lng', 'monthly_revenue']]
    .merge(competitor_features, on='location_id', how='left')
    .merge(poi_features,        on='location_id', how='left')
    .merge(buildings_features,   on='location_id', how='left')
    .merge(population_features, on='location_id', how='left')
    .merge(footfall_features,   on='location_id', how='left')
)

print(f"Shape: {features_df.shape}")
print(features_df.isna().sum())

Shape: (50, 29)
location_id                   0
lat                           0
lng                           0
monthly_revenue               0
competitor_count_1500m        0
nearest_competitor_m          0
poi_count_1500m               0
nearest_poi_m                 0
poi_restaurant_count_1500m    0
nearest_poi_restaurant_m      0
poi_bank_count_1500m          0
nearest_poi_bank_m            0
poi_school_count_1500m        0
nearest_poi_school_m          0
poi_bus_stop_count_1500m      0
nearest_poi_bus_stop_m        0
poi_park_count_1500m          0
nearest_poi_park_m            0
poi_pharmacy_count_1500m      0
nearest_poi_pharmacy_m        0
poi_hospital_count_1500m      0
nearest_poi_hospital_m        0
poi_mall_count_1500m          0
nearest_poi_mall_m            0
building_count_1500m          0
residential_ratio_1500m       0
population_1500m              0
signals_1500m                 0
unique_users_1500m            0
dtype: int64

In [21]:
features_df.to_csv('../data/processed/features.csv', index=False)
print(f"Saved features: {features_df.shape}")

Saved features: (50, 29)

## Summary

Feature engineering produced a training-ready dataset of 50 locations × 29 columns
(2 coordinates + target + 25 features), with no missing values.

A radius of 1500m was chosen after initial analysis at 500m yielded near-zero
variance across most categories (e.g. 0 competitors within 500m for 46/50
locations). 1500m provides meaningful signal while remaining within a realistic
catchment area for a grocery store. Building density is represented as a
residential ratio — share of residential buildings (single-family, two-family,
multifamily and collective housing) out of all buildings in radius — rather
than raw count, which better captures neighborhood character. Footfall features
are cached to `data/processed/footfall_features.parquet` to avoid recomputing
50 × ST_DWITHIN Snowflake queries (~13 min) on every notebook run.

This is the **initial version** of the feature set. Several aspects
may change after model training and evaluation in Task 3:

- Features with near-zero importance (e.g. sparse POI categories
  like `poi_bus_stop_count_1500m`, `poi_mall_count_1500m`)
  may be dropped.
- Radius may be revisited — different features may benefit
  from different catchment areas.
- Additional features (e.g. district-level encoding,
  building area density, household size) may be added
  in subsequent iterations based on model performance.
- Correlation between features (e.g. `population_1500m`
  and `signals_1500m`) will be examined in Task 3 —
  highly correlated features may be consolidated.

### Second iteration

Two more features will be engineered: `store_building_area`, which indicates the area of building in which the store is located, and `is_retail_building`, a binary flag which indicates if that building play a retail function

In [22]:
locs_proj = gdf_locations.to_crs('EPSG:2180')
buildings_proj = gdf_buildings.to_crs('EPSG:2180')

store_building = gpd.sjoin(
    locs_proj[['location_id', 'geometry']],
    buildings_proj[['geometry', 'area', 'funogolnabudynku_desc']],
    predicate='within',
    how='left'
)[['location_id', 'area', 'funogolnabudynku_desc']]

store_building = store_building.rename(columns={
    'area': 'store_building_area',
    'funogolnabudynku_desc': 'store_building_type'
})

# If a building is not found for a location, the nearest building is taken.
missing_ids = store_building[store_building['store_building_area'].isna()]['location_id']
missing = locs_proj[locs_proj['location_id'].isin(missing_ids)]

nearest_fallback = gpd.sjoin_nearest(
    missing[['location_id', 'geometry']],
    buildings_proj[['geometry', 'area', 'funogolnabudynku_desc']],
    how='left',
    distance_col='dist'
)[['location_id', 'area', 'funogolnabudynku_desc']]

store_building = store_building.set_index('location_id')
for _, row in nearest_fallback.iterrows():
    if pd.notna(row['area']):
        store_building.loc[row['location_id'], 'store_building_area'] = row['area']
        store_building.loc[row['location_id'], 'store_building_type'] = row['funogolnabudynku_desc']
store_building = store_building.reset_index()

store_building['is_retail_building'] = (
    store_building['store_building_type'] == 'budynkiHandlowoUslugowe'
).astype(int)

In [23]:
store_building

,location_id,store_building_area,store_building_type,is_retail_building
0,LOC_001,1187.77,budynkiHandlowoUslugowe,1
1,LOC_002,1218.72,budynkiBiurowe,0
2,LOC_003,4530.20,budynkiHandlowoUslugowe,1
3,LOC_004,94.78,budynkiMieszkalneJednorodzinne,0
4,LOC_005,1149.73,budynkiHandlowoUslugowe,1
5,LOC_006,1336.61,budynkiHandlowoUslugowe,1
6,LOC_007,932.03,budynkiHandlowoUslugowe,1
7,LOC_008,1170.33,budynkiHoteli,0
8,LOC_009,2931.16,budynkiHandlowoUslugowe,1
9,LOC_010,244.76,budynkiOTrzechIWiecejMieszkaniach,0
10,LOC_011,1183.65,budynkiHandlowoUslugowe,1
11,LOC_012,1097.31,budynkiHandlowoUslugowe,1
12,LOC_013,898.46,budynkiHandlowoUslugowe,1
13,LOC_014,1516.33,budynkiHandlowoUslugowe,1
14,LOC_015,1045.12,budynkiHandlowoUslugowe,1
15,LOC_016,2188.21,budynkiBiurowe,0
16,LOC_017,483.93,budynkiHandlowoUslugowe,1
17,LOC_018,869.92,budynkiHandlowoUslugowe,1
18,LOC_019,691.23,budynkiHandlowoUslugowe,1
19,LOC_020,2059.41,budynkiHandlowoUslugowe,1
20,LOC_021,1182.99,budynkiHandlowoUslugowe,1
21,LOC_022,1192.05,budynkiHandlowoUslugowe,1
22,LOC_023,1026.85,budynkiHandlowoUslugowe,1
23,LOC_024,1026.46,budynkiHandlowoUslugowe,1
24,LOC_025,1208.04,budynkiHandlowoUslugowe,1
25,LOC_026,94.89,budynkiMieszkalneJednorodzinne,0
26,LOC_027,1237.58,budynkiHandlowoUslugowe,1
27,LOC_028,1196.27,budynkiHandlowoUslugowe,1
28,LOC_029,682.69,budynkiHandlowoUslugowe,1
29,LOC_030,8037.64,budynkiHandlowoUslugowe,1
30,LOC_031,1363.70,budynkiHandlowoUslugowe,1
31,LOC_032,739.83,budynkiHandlowoUslugowe,1
32,LOC_033,1220.89,budynkiHandlowoUslugowe,1
33,LOC_034,703.35,budynkiHandlowoUslugowe,1
34,LOC_035,1239.77,budynkiHandlowoUslugowe,1
35,LOC_036,1133.29,budynkiHandlowoUslugowe,1
36,LOC_037,141.33,budynekGospodarstwaRolnego,0
37,LOC_038,974.51,budynkiHandlowoUslugowe,1
38,LOC_039,1665.94,budynkiSzkolIInstytucjiBadawczych,0
39,LOC_040,2758.66,budynkiHandlowoUslugowe,1
40,LOC_041,453.15,budynekGospodarstwaRolnego,0
41,LOC_042,411.00,budynkiHandlowoUslugowe,1
42,LOC_043,1126.46,budynkiHandlowoUslugowe,1
43,LOC_044,1338.52,budynkiHandlowoUslugowe,1
44,LOC_045,763.43,budynkiHandlowoUslugowe,1
45,LOC_046,1589.04,budynkiHandlowoUslugowe,1
46,LOC_047,1182.16,budynkiHandlowoUslugowe,1
47,LOC_048,1193.21,budynkiHandlowoUslugowe,1
48,LOC_049,724.81,budynkiOTrzechIWiecejMieszkaniach,0
49,LOC_050,1384.99,budynkiBiurowe,0

In [24]:
features_df = features_df.merge(
    store_building[['location_id', 'store_building_area', 'is_retail_building']],
    on='location_id',
    how='left'
)

In [25]:
features_df.to_csv('../data/processed/features_2.csv', index=False)
print(f"Saved features: {features_df.shape}")

Saved features: (50, 31)

### Third iteration (see notebook 03)

A third feature was explored during model training:
`signals_per_user = signals_1500m / unique_users_1500m` —
a proxy for visit frequency per unique visitor.
It was evaluated in `03_model_and_interpretation.ipynb`
alongside the model training process.
Result: marginal R² improvement (0.180 vs 0.175),
not statistically meaningful at n=50.